Repository AICoE/workshop-intern-bootcamp-git, pull requests merged in 2022-01, with the labels that each got.

#53 General maintainence of the project
  .pre-commit-config.yaml
  .prow.yaml
  4-fork.md
  attendees.txt
Labels: size/S

#54 Intern bootcamp
  attendees.txt
Labels: size/XS

#55 I m here! first commit upstream
  attendees.txt
Labels: size/XS

#58 Test upstream contribution from workshop!
  attendees.txt
Labels: size/XS, approved, ok-to-test

#57 Abatra's first upstream contribution
  attendees.txt
Labels: size/XS, approved
